name: Deploy Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AKIA5FTZFGFYXO4BVHFZ }}
        aws-secret-access-key: ${{ secrets.iEd2u37eYkXeM1Uh1CTrWUMith2e82ALWIOFJiod }}
        aws-region: us-east-1  # Change if needed

    - name: Sync website files to S3
      run: |
        aws s3 sync ./ s3://ashtonjcollinsportfolio.com/ --exclude ".git/*" --exclude ".github/*" --exclude "README.md" --delete
